### ISSUE TITLE
v1.10 breaks on python versions < 3.12

### ISSUE THREAD

**Issue by koffie** [quantorconsulting/mkdocs_build_plantuml#37]
In the latest version of this plugin the new https://docs.python.org/3/library/pathlib.html#pathlib.Path.walk command is now beeing used. This was only added in python 3.12 according to the documentation there.

Bulding the documentation using the v1.10 with python 3.11  leads to tracebacks like:

```Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 280, in build
    config.plugins.on_pre_build(config=config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 530, in on_pre_build
    return self.run_event('pre_build', config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 509, in run_event
    result = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_build_plantuml_plugin/plantuml.py", line 75, in on_pre_build
    for subdir, _, files in Path(root.src_dir).walk():
                            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'walk'
error: Command '['mkdocs', 'build', '--clean', '--config-file', '/builds/mike-mkdocsu8xn66i7.yml']' returned non-zero exit status 1.
```

Could either the Path.walk be replaced again by os.walk like it used to be before this commit: https://github.com/quantorconsulting/mkdocs_build_plantuml/commit/f62504bf3640602968ca3dad98d0a44e34eec870 ? Or could setup.py by updated to specify that this plugin needs python versions >= 3.12?

**Comment by christo-ph** [comment]
Thanks for reporting and sorry for the inconvenience. I changed the requirement in setup.py, released under [1.11.0](https://pypi.org/project/mkdocs-build-plantuml-plugin/)

Can you confirm this works?

**Comment by TheDutchDev** [comment]
We experienced the same issue. Any chance you could push 1.11.0 as default when installing with pip? 
For now I'll add the specific version to the build pipeline.

**Comment by christo-ph** [comment]
@KyleKing done

**Comment by KyleKing** [comment]
Thanks!!
